version: '3.3'

services:
  wordpress:
    depends_on:
      - db
    image: wordpress:5.0.1
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: Ngugit
    ports:
      - 18080:80
      - 18443:443
    networks:
      - back
  db:
    image: mysql:5.7
    restart: always
    volumes:
       - ./mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Ngugit
    networks:
      - back
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 18081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Ngugit
    networks:
      - back
networks:
  back:
